"""Updated Resume model

Revision ID: 613740c0a2ec
Revises: 
Create Date: 2025-10-24 19:29:26.953253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '613740c0a2ec'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('parsed_text', sa.Text(), nullable=True))
    op.add_column('resumes', sa.Column('skills', mysql.JSON(), nullable=True))
    op.add_column('resumes', sa.Column('education', mysql.JSON(), nullable=True))
    op.add_column('resumes', sa.Column('experience', mysql.JSON(), nullable=True))
    op.add_column('resumes', sa.Column('score', sa.Float(), nullable=True))
    op.add_column('resumes', sa.Column('ai_status', sa.String(length=50), nullable=True))
    op.drop_column('resumes', 'file_path')
    op.drop_column('resumes', 'is_primary')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('is_primary', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('resumes', sa.Column('file_path', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('resumes', 'ai_status')
    op.drop_column('resumes', 'score')
    op.drop_column('resumes', 'experience')
    op.drop_column('resumes', 'education')
    op.drop_column('resumes', 'skills')
    op.drop_column('resumes', 'parsed_text')
    # ### end Alembic commands ###
